# saqib/team-s/user

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

# add in server block
   
    server {
        listen 8002;
        server_name localhost;

        location / {
            
            root /usr/share/nginx/html;
            index index.html;
        }
    }

    server {
        listen 8003;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index2.html;
        }
    }
}
